# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "node1" do |node1|
    node1.vm.box = "bento/centos-6.8"
    node1.vm.hostname = "node1"

    node1.vm.network :private_network, ip: "192.168.50.4"

    node1.vm.provider "virtualbox" do |v|
      v.cpus = 4
      v.memory = 2048
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end

    node1.vm.provision :shell do |s|
      s.path = 'utils/provision.sh'
      s.keep_color = true
    end
  end

  config.vm.define "node9" do |node9|
    node9.vm.box = "bento/centos-6.8"
    node9.vm.hostname = "node9"

    node9.vm.network :private_network, ip: "192.168.50.9"

    node9.vm.provider "virtualbox" do |v|
      v.cpus = 1
      v.memory = 512
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end

    node9.vm.provision :shell do |s|
      s.path = 'utils/provision.sh'
      s.keep_color = true
    end
  end

  config.vm.define 'controller' do |machine|
    machine.vm.box = "bento/centos-6.8"
    machine.vm.hostname = "controller"

    machine.vm.network "private_network", ip: "192.168.50.8"

    machine.vm.provider "virtualbox" do |v|
      v.cpus = 2
      v.memory = 512
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end

    machine.vm.synced_folder ".", "/vagrant"
    machine.vm.synced_folder "..", "/home/vagrant/roles"

    machine.vm.provision :ansible_local do |ansible|
      ansible.playbook       = "integration/install.yml"
      ansible.verbose        = true
      ansible.install        = true
#      ansible.tags           = "admin"
#      ansible.skip_tags      = "always"
#      ansible.skip_tags      = "admin"
      ansible.limit          = "all"
      ansible.inventory_path = "integration/hosts"
    end
  end

end
